version: '2'
services:
#    changedetection.io:
#      image: dgtlmoon/changedetection.io
#      container_name: changedetection.io
#      hostname: changedetection.io
#      volumes:
#        - changedetection-data:/datastore
#        - .:/app

  #    environment:
  #      - PUID=1000
  #      - PGID=1000
  #      - WEBDRIVER_URL="http://browser-chrome:4444/wd/hub"
  #        Proxy support example.
  #      - HTTP_PROXY="socks5h://10.10.1.10:1080"
  #      - HTTPS_PROXY="socks5h://10.10.1.10:1080"
  #        An exclude list (useful for notification URLs above) can be specified by with
  #      - NO_PROXY="localhost,192.168.0.0/24"
  #        Base URL of your changedetection.io install (Added to notification alert
  #      - BASE_URL="https://mysite.com"

#      ports:
#        - 6500:5000
#      restart: always

    browser-chrome:
        hostname: browser-chrome
        image: selenium/standalone-chrome-debug:3.141.59
        ports:
          - 4444:4444
#        networks:
#            - opencart
        environment:
            - VNC_NO_PASSWORD=1
        volumes:
            - .:/poop
            # For downloads in the browser, for example PDF patterns
            # NOTE!!!! THIS MUST BE CHMOD 777 because selenium will write to it under who knows what UID..
            - ./tests/codeception/_output/downloads:/var/www/html/tests/codeception/_output/downloads
            # Uploads
            - ./tests/codeception/_data:/var/www/html/tests/codeception/_data
            # Workaround to avoid the browser crashing inside a docker container
            # See https://github.com/SeleniumHQ/docker-selenium#quick-start
            - /dev/shm:/dev/shm


volumes:
  changedetection-data:

