version: '2'
services:
  changedetection:
    build: .
    hostname: changedetection.io
    volumes:
      - changedetection-data:/datastore
#    environment:
#        Proxy support example.
#      - HTTP_PROXY="socks5h://10.10.1.10:1080"
#      - HTTPS_PROXY="socks5h://10.10.1.10:1080"
#        An exclude list (useful for notification URLs above) can be specified by with
#      - NO_PROXY="localhost,192.168.0.0/24"
#        Base URL of your changedetection.io install (Added to notification alert
#      - BASE_URL="https://mysite.com"

#   Not needed because we are port's on the host via NGINX
#    ports:
#      - 5000:5000
    restart: unless-stopped
    networks:
        changenet:
            aliases:
                - flask-app
  nginx:
    image: nginx:1
    ports:
        - 80:80
    volumes:
        - ./docker-configs/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
        changenet:
    restart: unless-stopped

volumes:
  changedetection-data:
networks:
    changenet:


