version: '2'

services:
  changedetection:
    image: dgtlmoon/changedetection.io
    hostname: changedetection.io
    volumes:
      - changedetection-data:/datastore
    ports:
      - 5000:5000
    restart: always
    networks:
        changenet:
            aliases:
                - flask-app

  nginx:
    image: nginx:1
    ports:
        - 80:80
    volumes:
        - ./docker-configs/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
        changenet:

volumes:
  changedetection-data:
networks:
    changenet:
