version: '2'
services:
    changedetection.io:
      image: dgtlmoon/changedetection.io:javascript
      container_name: changedetection.io
      hostname: changedetection.io
      volumes:
        - changedetection-data:/datastore

  #    environment:
  #      - PUID=1000
  #      - PGID=1000
  #      - WEBDRIVER_URL="http://browser-chrome:4444/wd/hub"
  #        Proxy support example.
  #      - HTTP_PROXY="socks5h://10.10.1.10:1080"
  #      - HTTPS_PROXY="socks5h://10.10.1.10:1080"
  #        An exclude list (useful for notification URLs above) can be specified by with
  #      - NO_PROXY="localhost,192.168.0.0/24"
  #        Base URL of your changedetection.io install (Added to notification alert
  #      - BASE_URL="https://mysite.com"

      ports:
        - 5000:5000
      restart: always

    browser-chrome:
        hostname: browser-chrome
        image: selenium/standalone-chrome-debug:3.141.59
        ports:
          - 4444:4444
        environment:
            - VNC_NO_PASSWORD=1
        volumes:
            # Workaround to avoid the browser crashing inside a docker container
            # See https://github.com/SeleniumHQ/docker-selenium#quick-start
            - /dev/shm:/dev/shm
        restart: always

volumes:
  changedetection-data:

