name: ChangeDetection.io Test

# Triggers the workflow on push or pull request events
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest
        run: |
          # Each test is totally isolated and performs its own cleanup/reset
          cd backend; ./run_all_tests.sh

      - name: Test that pip builds without error
        run: |
          python3 setup.py bdist_wheel

# test the dockerfile build works
# test the pip install builds
# 2160  python3 setup.py bdist_wheel
# 2161  python3 -m pip install dist/changedetection.io-0.38.2-py3-none-any.whl --force

